---
- name: apt-get update
  apt:
    update_cache: yes
    upgrade: safe

- name: Install dependencies
  apt:
    name:
      - postfix
      - ufw

- name: Update Postfix configuration
  lineinfile:
    dest: "/etc/postfix/main.cf"
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }} ="
    mode: 0644
  with_items:
    - name: myhostname
      value: "{{ mail_domain }}"
    - name: virtual_alias_domains
      value: "{{ mail_domain }}"
    - name: virtual_alias_maps
      value: "hash:/etc/postfix/virtual"
  notify: Restart Postfix

- name: Create forwarding addresses
  lineinfile:
    dest: "/etc/postfix/virtual"
    line: "{{ item.source }} {{ item.target }}"
    regexp: "^{{ item.source }} "
    mode: 0644
    create: yes
  with_items: "{{ mail_forwarding }}"
  notify: Restart Postfix

- name: Ensure Postfix is started and enabled at boot.
  service:
    name: postfix
    state: started
    enabled: true

- name: Enable SMTP ports
  ufw:
    rule: allow
    port: smtp

- name: Enable ufw
  ufw:
    state: enabled
