version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Create virtualenv
          command: |
            cd ~
            python -m virtualenv ~/venv
      - run:
          name: Install python dependencies
          command: |
            . ~/venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/venv"
      - run:
          command: molecule test