---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint --force-color
  flake8
platforms:
  - name: ubuntu-focal-mail
    image: ubuntu:focal
    dockerfile: Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
